project:
  title: "capacity-development"
  output-dir: _slides

format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/d4dm.png
    css: styles.css
    footer: "Tam Anh Oxford Partnership"

author:
  name: Ernest Guevarra
  email: ernest@guevarra.io
  affiliation: University of Oxford