project:
  title: "capacity-development"
  output-dir: _slides

format:
  revealjs: 
    slide-number: true
    # chalkboard: 
    #   buttons: false
    preview-links: auto
    logo: images/top_logo.jpg
    css: styles.css
    footer: "Tam Anh Oxford Partnership"
    embed-resources: true
  pptx: default

# author:
#   name: Ernest Guevarra
#   email: ernest@guevarra.io
#   affiliation: University of Oxford