project:
  title: "capacity-development"
  output-dir: _site
  render:
    - "*.qmd"
    - "!LICENSE.md"
    - "!NEWS.md"

format:
  revealjs: 
    slide-number: true
    # chalkboard: 
    #   buttons: false
    preview-links: auto
    logo: images/top_logo.jpg
    css: styles.css
    footer: "Tam Anh Oxford Partnership"
    embed-resources: true
  pptx: default

