---
title: "Tam Anh Oxford Partnership Capacity Development"
format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: false
---

## Introduction to Research Methods

**Session** | **Links**
:--- | :---
Research Data Managemet | [HTML](data-management/index.html){.external target="_blank"} [PPTX](data-management/index.pptx) [PDF](data-management/data_management.pdf)


## Data Concepts and Applications

**Session** | **Links**
:--- | :---
**Session 1:** Global landscape of data governance institutions and framework | [HTML](data-frameworks/01-global-landscape.html){.external target="_blank"} [PPTX](data-frameworks/01-global-landscape.pptx) [PDF](data-frameworks/01-global-landscape.pdf)
**Session 2:** Case Study: The UK Data Landscape | [HTML](data-frameworks/02-uk-landscape.html){.external target="_blank"} [PPTX](data-frameworks/02-uk-landscape.pptx) [PDF](data-frameworks/02-uk-landscape.pdf)
**Session 3:** Case Study: Singapore’s Smart Nation, Open Government Products, and Singapore Government Tech Stack | [HTML](data-frameworks/03-singapore-open-government.html){.external target="_blank"} [PPTX](data-frameworks/03-singapore-open-government.pptx) [PDF](data-frameworks/03-singapore-open-government.pdf)
**Session 4:** Case Study: The United Nations and its technological and data challenges | [HTML](data-frameworks/04-un-tech.html){.external target="_blank"} [PPTX](data-frameworks/04-un-tech.pptx) [PDF](data-frameworks/04-un-tech.pdf)
**Session 5:** Guiding principles on policymaking on national level data governance frameworks | [HTML](data-frameworks/05-principles-poliycmaking.html){.external target="_blank"} [PPTX](data-frameworks/05-principles-poliycmaking.pptx) [PDF](data-frameworks/05-principles-poliycmaking.pdf)
**Session 6:** Best practices in setting up and implementing data governance structures | [HTML](data-frameworks/06-best-practice-data-governance.html){.external target="_blank"} [PPTX](data-frameworks/06-best-practice-data-governance.pptx) [PDF](data-frameworks/06-best-practice-data-governance.pdf)
**Session 7:** Global landscape of available technologies for data | [HTML](data-frameworks/07-global-landscape-technologies.html){.external target="_blank"} [PPTX](data-frameworks/07-global-landscape-technologies.pptx) [PDF](data-frameworks/07-global-landscape-technologies.pdf)
**Session 8:** The landscape of technologies for data in Vietnam | [HTML](data-frameworks/08-vietnam-landscape-technologies.html){.external target="_blank"} [PPTX](data-frameworks/08-vietnam-landscape-technologies.pptx) [PDF](data-frameworks/08-vietnam-landscape-technologies.pdf)
**Session 9:** Global landscape of human resources for data | [HTML](data-frameworks/09-global-landscape-human-resources.html){.external target="_blank"} [PPTX](data-frameworks/09-global-landscape-human-resources.pptx) [PDF](data-frameworks/09-global-landscape-human-resources.pdf)
**Session 10:** The landscape of human resources for data in Vietnam | [HTML](data-frameworks/10-vietnam-landscape-human-resources.html){.external target="_blank"} [PPTX](data-frameworks/10-vietnam-landscape-human-resources.pptx) [PDF](data-frameworks/10-vietnam-landscape-human-resources.pdf)
**Session 11:** Guiding principles and best practices for data capacity building | [HTML](data-frameworks/11-best-practice-capacity-building.html){.external target="_blank"} [PPTX](data-frameworks/11-best-practice-capacity-building.pptx) [PDF](data-frameworks/11-best-practice-capacity-building.pdf)
**Session 12:** Financing data governance | [HTML](data-frameworks/12-financing-data.html){.external target="_blank"} [PPTX](data-frameworks/12-financing-data.pptx) [POF](data-frameworks/12-financing-data.pdf)
**Session 13:** Manager personas for successful building and implementation of data governance structures and frameworks for Vietnam | [HTML](data-frameworks/13-manager-personas.html){.external target="_blank"} [PPTX](data-frameworks/13-manager-personas.pptx) [PDF](data-frameworks/13-manager-personas.pdf)
